# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'MessagingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  
  # Pods for MessagingApp

  target 'MessagingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MessagingAppUITests' do
    # Pods for testing
  end

end
